### ISSUE TITLE
What version of python should be used to replicate the results?

### ISSUE THREAD

**Issue by xaviergonzalez** [machine-discovery/deer#39]
I am trying to run the code in the repo but am not being successful. Here are the steps I'm taking.

1. I git clone the current version of the repo

2. I set up a virtual environment using python3.9

3. Inside of the repo, I run `pip install --upgrade -e .[replication]` as instructed.

4. I try to run the demo script as instructed `python deer/demo.py`

I get the following error:

```
(deer-rep-attempt) [/user/deer-replication-attempt/deer]$ python deer/demo.py
Traceback (most recent call last):
  File "/user/deer-replication-attempt/deer/deer/demo.py", line 6, in <module>
    import equinox as eqx
  File "/user/venvs/deer-rep-attempt/lib/python3.9/site-packages/equinox/__init__.py", line 3, in <module>
    from . import debug as debug, internal as internal, nn as nn
  File "/user/venvs/deer-rep-attempt/lib/python3.9/site-packages/equinox/debug/__init__.py", line 1, in <module>
    from ._announce_transform import announce_transform as announce_transform
  File "/user/venvs/deer-rep-attempt/lib/python3.9/site-packages/equinox/debug/_announce_transform.py", line 11, in <module>
    from .._filters import combine, is_array, partition
  File "/user/venvs/deer-rep-attempt/lib/python3.9/site-packages/equinox/_filters.py", line 11, in <module>
    AxisSpec = Union[bool, Callable[[Any], bool]]
  File "/share/software/user/open/python/3.9.0/lib/python3.9/typing.py", line 243, in inner
    return func(*args, **kwds)
  File "/share/software/user/open/python/3.9.0/lib/python3.9/typing.py", line 316, in __getitem__
    return self._getitem(self, parameters)
  File "/share/software/user/open/python/3.9.0/lib/python3.9/typing.py", line 421, in Union
    parameters = _remove_dups_flatten(parameters)
  File "/share/software/user/open/python/3.9.0/lib/python3.9/typing.py", line 215, in _remove_dups_flatten
    all_params = set(params)
TypeError: unhashable type: 'list'
```

I'm wondering if you used a different version of python, and, if so, if you could specify which version of python is needed to replicate the results?

I also tried with python3.6 and could not even pip install deer.

**Comment by mfkasim1** [comment]
I used python 3.9. Looking at your error, it seems the error is raised just when it imports equinox, so I'm not sure if it's related to DEER.

**Comment by xaviergonzalez** [comment]
That is good to know. However, I'm only installing equinox using your `setup.py` file instructions. Can you check if your provided instructions result in the same error?
